### ISSUE TITLE
Init entities

### ISSUE THREAD

**Issue by tulx17** [etases/EduBlock.RS#1]
Role: ANYONE, STUDENT, STAFF, TEACHER, ADMIN

- Account: **Id**, Username, HashedPassword, SaltedPassword, Role
- Profile: **AccountId**, FirstName, LastName, Avatar, DateOfBirth, Address, Phone, Email
- Student: **AccountId**, Ethnic, FatherName, FatherJob, MotherName, MotherJob, HomeTown
- Subject: **Id**, SubjectName

- Class: **Id**, ClassName, Grade
- ClassStudent: **Id**, ClassId, AccountId
- ClassTeacher: **Id**, ClassId, AccountId, SubjectId

- RecordEntry: **Id**, SubjectId, FirstHalfScore, SecondHalfScore, Average, TeacherId
- Record: **Id**, ClassId, StudentId, RecordEntryId
- PendingRecordEntry: **Id**, SubjectId, FirstHalfScore, SecondHalfScore, Average, TeacherId

**Comment by HSGamer** [comment]
![image](https://user-images.githubusercontent.com/25300232/189882916-c9b27f9d-e18c-447a-9074-4ad3bc918c93.png)
