### ISSUE TITLE
Student request record validation

### ISSUE THREAD

**Issue by tulx17** [etases/EduBlock.RS#19]

**Comment by khoatvbattu** [comment]
Có input rồi, tạo cái PendingRecordEntry là cái input đó nhưng mà giờ làm sao thêm input vô session  @@
query lấy cái EntryRecord từ Record bằng userId, lấy ra bỏ vô cái List<PendingRecordEntryOutPut>
rồi làm sao với cái input đây .__.

**Comment by HSGamer** [comment]
Chỉ cần lưu cái PendingRecordEntry là được.

Cái RecordEntry chỉ lưu những cái đã xác minh rồi.

**Comment by HSGamer** [comment]
Coi mấy cái ClassCreate bên StaffHandler rồi theo tương tự.

**Comment by khoatvbattu** [comment]
vậy là ctx.json k cần trả data ra phải hong

**Comment by HSGamer** [comment]
không cần trả, dùng cái `Response` để trả ra errorCode với message là được rồi

**Comment by khoatvbattu** [comment]
cho hỏi lại cái là mình lấy data của RecordEntry từ bảng Record của thằng Student đem lưu qua bảng PendingRecordEntry đúng hong ?

**Comment by HSGamer** [comment]
Không, tạo mới

**Comment by HSGamer** [comment]
Làm vậy để lưu luôn mấy cái Record cũ sau khi đã xác minh.

Giống như tạo mới một yêu cầu chỉnh sửa điểm cho một môn ấy.

**Comment by khoatvbattu** [comment]
À ý là tạo mới rỗng bên bảng Pending cho mấy người Verifier người ta nhập số (input)

**Comment by HSGamer** [comment]
Không, Ý là cái Input đã đưa ra số điểm rồi, việc của bên verifier là xem coi có duyệt cái điểm này không

Nên cái Input đem các trường số điểm qua bên pending luôn

**Comment by khoatvbattu** [comment]
À là cái hàm này đc dùng ( kích hoạt ) khi mà thằng Student đã nhập điểm xong và bấm nút Request Validation, xong lấy cái input mà thằng Student ghi vô trước đó sẽ lưu vô cái Pending cho Verifier lấy ra kiểm tra

**Comment by khoatvbattu** [comment]
A lúc đầu nhầm lẫn là Request lấy điểm từ Record qua cho thằng Verifier luôn mà thằng Student k nhập gì :v damn

**Comment by khoatvbattu** [comment]
Bởi vậy mà k biết tạo cái input chi rồi lẫn quẫn loop kẹt luôn .__.
